dist: trusty
language: erlang
notifications:
  email: false
otp_release:
  - 22.2
  - 22.1.8
  - 22.0.7
  - 21.3.8.1
  - 21.2.7
  - 21.1.4
  - 21.0.9
  - 20.3.8.22
  - 20.1.7
  - 20.0
  - 19.3.6
  - 19.2
  - 19.0
  - 18.3
  - 18.2.1
  - 18.1
  - 18.0
script: rebar compile && rebar eunit -v
